# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: honeycombio/honeyaws
  pullPolicy: IfNotPresent
  docker_tag: latest


nameOverride: honey-aws-lb
fullnameOverride: ""

nodeSelector:
  role: ops

tolerations: []

affinity: {}


env:
  
## Specify AWS load balancers to monitor.
## E.g

# honeyMonitoredLoadBalancers:
#   my-aws-load-balancer-name:            # As named on AWS Load Balancers console
#     type: "alb"                         # [alb|elb]
#     dataset: "honeycomb-dataset-name"
#     samplerate: 20                      # 1 out of 20
#     writekey: "my-honeycomb-writekey"   # From honeycomb account
